/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.devpl.java-conventions")
}

dependencies {
    api("org.slf4j:slf4j-api:2.0.7")
    api("org.jetbrains:annotations:24.0.1")
    api("ch.qos.logback:logback-classic:1.4.8")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.11.0-M1")
    testImplementation("org.dom4j:dom4j:2.1.4")
    testImplementation("org.apache.commons:commons-dbcp2:2.11.0")
    testImplementation("mysql:mysql-connector-java:8.0.33")
}

group = "org.example"
description = "apache-ddlutils"

java {
    withJavadocJar()
}
