/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.devpl.java-conventions")
}

dependencies {
    api(project(":devpl-codegen"))
    testImplementation(Libs.jupiter)
}

group = "org.example"
description = "sqltemplate"

java {
    withJavadocJar()
}
