package org.apache.ddlutils.io;

import org.apache.ddlutils.util.NestableRuntimeException;

import java.io.Serial;

/**
 * Exception generated by {@link org.apache.ddlutils.io.DataSink} implementations.
 */
public class DataSinkException extends NestableRuntimeException {
    /**
     * Unique id for serialization purposes.
     */
    @Serial
    private static final long serialVersionUID = 6790909409839782437L;

    /**
     * Creates a new exception object.
     */
    public DataSinkException() {
        super();
    }

    /**
     * Creates a new exception object.
     *
     * @param message The exception message
     */
    public DataSinkException(String message) {
        super(message);
    }

    /**
     * Creates a new exception object.
     *
     * @param baseEx The base exception
     */
    public DataSinkException(Throwable baseEx) {
        super(baseEx);
    }

    /**
     * Creates a new exception object.
     *
     * @param message The exception message
     * @param baseEx  The base exception
     */
    public DataSinkException(String message, Throwable baseEx) {
        super(message, baseEx);
    }
}
