package org.apache.ddlutils.io.converters;

import org.apache.ddlutils.util.NestableRuntimeException;

/**
 * Exception generated by {@link org.apache.ddlutils.io.converters.SqlTypeConverter} implementations.
 */
public class ConversionException extends NestableRuntimeException {

    /**
     * Creates a new exception object.
     */
    public ConversionException() {
        super();
    }

    /**
     * Creates a new exception object.
     *
     * @param message The exception message
     */
    public ConversionException(String message) {
        super(message);
    }

    /**
     * Creates a new exception object.
     *
     * @param baseEx The base exception
     */
    public ConversionException(Throwable baseEx) {
        super(baseEx);
    }

    /**
     * Creates a new exception object.
     *
     * @param message The exception message
     * @param baseEx  The base exception
     */
    public ConversionException(String message, Throwable baseEx) {
        super(message, baseEx);
    }
}
