server:
    port: 8088
    servlet:
        context-path: /devpl

spring:
    profiles:
        active: dev
    datasource:
        # MySQL
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/devpl?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&useAffectedRows=true&allowMultiQueries=true
        username: root
        password: 123456

# 需要指定对应的模板
codegen:
    template: /codegen/templates

# mybatis-plus配置
mybatis-plus:
    mapper-locations: classpath:/mapper/*.xml
    typeAliasesPackage: io.devpl.backend.entity
    global-config:
        db-config:
            id-type: AUTO
        banner: false
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false # 关闭或开启 Mybatis 二级缓存，默认为 true。
        call-setters-on-nulls: true
        jdbc-type-for-null: 'null'
        log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl # 不输出日志
        # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台输出日志
    configuration-properties:
        prefix:
        blobType: BLOB
        boolValue: TRUE
