server:
    port: 8088
    servlet:
        context-path: /devpl

spring:
    application:
        name: Devpl
        description: Devpl for backend
    profiles:
        active: dev
    datasource:
        # MySQL
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/devpl?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&useAffectedRows=true&allowMultiQueries=true
        username: root
        password: 123456
    servlet:
        multipart:
            # 文件上传最大限制
            max-file-size: 50MB
            # 请求数据最大限制
            max-request-size: 10MB

# 需要指定对应的模板
codegen:
    template: /codegen/templates

# mybatis-plus配置
mybatis-plus:
    mapper-locations: classpath:/mapper/*.xml
    typeAliasesPackage: io.devpl.backend.entity
    global-config:
        db-config:
            id-type: AUTO
            capital-mode: off
            logic-delete-field: is_deleted
        banner: false
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false # 关闭或开启 Mybatis 二级缓存，默认为 true。
        call-setters-on-nulls: true
        jdbc-type-for-null: 'null'
        log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl # 不输出日志
        # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台输出日志
    configuration-properties:
        prefix:
        blobType: BLOB
        boolValue: TRUE

# pagehelper 配置
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql

devpl:
    file:
        upload:
            root: /Temp # 文件上传根目录
        codegen:
            root: /Temp # 代码生成根目录
    codegen:
        template:
            local-location: ${user.home}/Temp # 模板存放根目录，支持SpringEL表达式
    package:
        entity: io.devpl.backend.entity # 实体类包名
    db:
        name: devpl # 本系统数据库名称
        driver:
            location:  # 驱动保存位置，默认db/drivers
        backup:
            # 是否开启数据库备份，启动时备份数据库的表结构及全量数据
            enabled: false
