import { MenuList, MenuResponse } from "@/types/menu";
import { resolve } from "path";


/**
 * 菜单数据
 */
let menu: MenuList = [
  {
    menu_id: 9,
    [MENU_TITLE]: "列表页",
    [MENU_PATH]: "/list",
    [MENU_KEY]: "list",
    [MENU_PARENTKEY]: "",
    [MENU_ICON]: "icon_list",
    [MENU_KEEPALIVE]: "false",
    order: 1,
  },
  {
    menu_id: 10,
    [MENU_TITLE]: "卡片列表",
    [MENU_PATH]: "/card",
    [MENU_KEY]: "listCard",
    [MENU_PARENTKEY]: "list",
    [MENU_ICON]: "",
    [MENU_KEEPALIVE]: "false",
    order: 5485,
  },
  {
    menu_id: 11,
    [MENU_TITLE]: "查询列表",
    [MENU_PATH]: "/search",
    [MENU_KEY]: "listSearch",
    [MENU_PARENTKEY]: "list",
    [MENU_ICON]: "",
    [MENU_KEEPALIVE]: "false",
    order: 9588,
  },
  {
    menu_id: 7,
    [MENU_TITLE]: "表单页",
    [MENU_PATH]: "/form",
    [MENU_KEY]: "from",
    [MENU_PARENTKEY]: "",
    [MENU_ICON]: "icon_form",
    [MENU_KEEPALIVE]: "false",
    order: 3,
  },
  {
    menu_id: 6,
    [MENU_TITLE]: "基础表单",
    [MENU_PATH]: "/index",
    [MENU_KEY]: "formIndex",
    [MENU_PARENTKEY]: "from",
    [MENU_ICON]: "",
    [MENU_KEEPALIVE]: "false",
    order: 9654,
  },
  {
    menu_id: 1,
    [MENU_TITLE]: "详情页",
    [MENU_PATH]: "/details",
    [MENU_KEY]: "details",
    [MENU_PARENTKEY]: "",
    [MENU_ICON]: "icon_edit",
    [MENU_KEEPALIVE]: "false",
    order: 3,
  },
  {
    menu_id: 2,
    [MENU_TITLE]: "个人中心",
    [MENU_PATH]: "/person",
    [MENU_KEY]: "detailsPerson",
    [MENU_PARENTKEY]: "details",
    [MENU_ICON]: "icon_infopersonal",
    [MENU_KEEPALIVE]: "false",
    order: 9998,
  },
  {
    menu_id: 16,
    [MENU_TITLE]: "结果页",
    [MENU_PATH]: "/result",
    [MENU_KEY]: "result",
    [MENU_PARENTKEY]: "",
    [MENU_ICON]: "icon_voiceprint",
    [MENU_KEEPALIVE]: "false",
    order: 4,
  },
  {
    menu_id: 3,
    [MENU_TITLE]: "403",
    [MENU_PATH]: "/403",
    [MENU_KEY]: "error403",
    [MENU_PARENTKEY]: "result",
    [MENU_ICON]: "icon_locking",
    [MENU_KEEPALIVE]: "false",
    order: 0,
  },
  {
    menu_id: 4,
    [MENU_TITLE]: "404",
    [MENU_PATH]: "/404",
    [MENU_KEY]: "error404",
    [MENU_PARENTKEY]: "result",
    [MENU_ICON]: "icon_close",
    [MENU_KEEPALIVE]: "false",
    order: 1,
  },
  {
    menu_id: 5,
    [MENU_TITLE]: "500",
    [MENU_PATH]: "/500",
    [MENU_KEY]: "error500",
    [MENU_PARENTKEY]: "result",
    [MENU_ICON]: "icon_privacy_closed",
    [MENU_KEEPALIVE]: "false",
    order: 4568,
  },
  {
    menu_id: 17,
    [MENU_TITLE]: "统计",
    [MENU_PATH]: "/statistics",
    [MENU_KEY]: "statistics",
    [MENU_PARENTKEY]: "",
    [MENU_ICON]: "icon_MTR",
    [MENU_KEEPALIVE]: "true",
    order: 5,
  },
  {
    menu_id: 18,
    [MENU_TITLE]: "访客统计",
    [MENU_PATH]: "/visitor",
    [MENU_KEY]: "visitor",
    [MENU_PARENTKEY]: "statistics",
    [MENU_ICON]: "icon_addresslist",
    [MENU_KEEPALIVE]: "true",
    order: 1,
  },
  {
    menu_id: 12,
    [MENU_TITLE]: "权限管理",
    [MENU_PATH]: "/power",
    [MENU_KEY]: "power",
    [MENU_PARENTKEY]: "",
    [MENU_ICON]: "icon_set",
    [MENU_KEEPALIVE]: "false",
    order: 9,
  },
  {
    menu_id: 14,
    [MENU_TITLE]: "权限类别",
    [MENU_PATH]: "/type",
    [MENU_KEY]: "powerType",
    [MENU_PARENTKEY]: "power",
    [MENU_ICON]: "icon_safety",
    [MENU_KEEPALIVE]: "true",
    order: 12,
  },
  {
    menu_id: 13,
    [MENU_TITLE]: "菜单管理",
    [MENU_PATH]: "/menu",
    [MENU_KEY]: "powerMenu",
    [MENU_PARENTKEY]: "power",
    [MENU_ICON]: "icon_menu",
    [MENU_KEEPALIVE]: "true",
    order: 1475,
  },
  {
    menu_id: 15,
    [MENU_TITLE]: "用户管理",
    [MENU_PATH]: "/user",
    [MENU_KEY]: "powerUser",
    [MENU_PARENTKEY]: "power",
    [MENU_ICON]: "icon_infopersonal",
    [MENU_KEEPALIVE]: "true",
    order: 1593,
  },
  {
    menu_id: 8,
    [MENU_TITLE]: "图标库",
    [MENU_PATH]: "/icons",
    [MENU_KEY]: "icons",
    [MENU_PARENTKEY]: "",
    [MENU_ICON]: "icon_pen",
    [MENU_KEEPALIVE]: "true",
    order: 10,
  },
  {
    menu_id: 33,
    [MENU_TITLE]: "测试页面",
    [MENU_PATH]: "/test",
    [MENU_KEY]: "powerTest",
    [MENU_PARENTKEY]: "power",
    [MENU_ICON]: "icon_list",
    [MENU_KEEPALIVE]: "false",
    order: 1594,
  },
];

export const getSideMenus = () : Promise<MenuResponse> => {
  return new Promise<MenuResponse>((reslove) => {
      resolve(menu)
  })
}

